export const TAG_LIST = {
	"div": { "isPaired": true, "hasParams": true },
	"span": { "isPaired": true, "hasParams": true },
	"p": { "isPaired": true, "hasParams": true },
	"img": { "isPaired": false, "hasParams": true },
	"input": { "isPaired": false, "hasParams": true },
	"br": { "isPaired": false, "hasParams": false },
	"hr": { "isPaired": false, "hasParams": false },
	"a": { "isPaired": true, "hasParams": true },
	"ul": { "isPaired": true, "hasParams": true },
	"ol": { "isPaired": true, "hasParams": true },
	"li": { "isPaired": true, "hasParams": true },
	"h1": { "isPaired": true, "hasParams": true },
	"section": { "isPaired": true, "hasParams": true },
	"article": { "isPaired": true, "hasParams": true },
	"nav": { "isPaired": true, "hasParams": true },
	"footer": { "isPaired": true, "hasParams": true },
	"header": { "isPaired": true, "hasParams": true },
	"button": { "isPaired": true, "hasParams": true },
	"form": { "isPaired": true, "hasParams": true },
	"textarea": { "isPaired": true, "hasParams": true },
	"meta": { "isPaired": false, "hasParams": true },
	"link": { "isPaired": false, "hasParams": true },
	"script": { "isPaired": true, "hasParams": true },
	"style": { "isPaired": true, "hasParams": true },
	"label": { "isPaired": true, "hasParams": true },
} as const

export type ValidTagName = keyof typeof TAG_LIST;