name: CI

on:
  push:
    branches:
      - main
      - 'feat/initial-logic'
  pull_request:
    branches:
      - main
      - 'feat/initial-logic'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: |
          make lint
          make test